name: Build and Deploy Lammy Safety Docker Container

on:
  workflow_dispatch:

jobs:
  build-publish-worker-docker:
    name: Lemmy Safety Container
    runs-on: ubuntu-latest
    steps:
    - name: "✔️ Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Free disk space
    #   uses: jlumbroso/free-disk-space@main
    #   with:
    #     tool-cache: false
    - name: "Build and Publish Container to Github Container Registry"
      run: |
        docker build -t ghcr.io/db0/lemmy-safety:${{ github.ref_name }} .
        docker push ghcr.io/db0/lemmy-safety:${{ github.ref_name }}